#!/usr/bin/env bash

echo "{ _remote:n_ }   -- {_remote:n_}"
echo "{ _remote:f_ }   -- {_remote:f_}"
echo "{ _remote:p_ }   -- {_remote:p_}"
echo "{ _name_ }       -- {_name_}    "
echo "{ _path:r_ }     -- {_path:r_}  "
echo "{ _path:a_ }     -- {_path:a_}  "
echo "{ _nesting_ }    -- {_nesting_} "
echo "{ _branch:n_ }   -- {_branch:n_}"
echo "{ _branch:c_ }   -- {_branch:c_}"
echo "{ _hash:f_ }     -- {_hash:f_}  "
echo "{ _hash:8_ }     -- {_hash:8_}  "
echo "{ _hash:80_ }    -- {_hash:80_} "
echo "{ _commit:c_ }   -- {_commit:c_}"
echo "{ _author:e_ }   -- {_author:e_}"
echo "{ _author:n_ }   -- {_author:n_}"
echo "{ _time:r_ }     -- {_time:r_}  "
echo "{ _time:rc_ }    -- {_time:rc_} "
echo "{ _time:a_ }     -- {_time:a_}  "
echo "{ _dirty_ }      -- {_dirty_}   "
echo "{ _bare_ }       -- {_bare_}    "
echo "{ _size_ }       -- {_size_}    "
echo "{ _language_ }   -- {_language_}"
echo "{ _upstream_ }   -- {_upstream_}"
echo "{ _ahead_ }      -- {_ahead_}"
echo "{ _behind_ }     -- {_behind_}"
echo "{ _state_ }      -- {_state_}"
echo "{ _shallow_ }    -- {_shallow_}"
echo "{ _remote:c_ }   -- {_remote:c_}"
echo "{ _tag:c_ }      -- {_tag:c_}"
echo "{ _worktree:c_ } -- {_worktree:c_}"
echo "{ _stash:c_ }    -- {_stash:c_}"
echo "{ _user:n_ }     -- {_user:n_}"
echo "{ _user:e_ }     -- {_user:e_}"
echo "{ _commit:s_ }   -- {_commit:s_}"
