mod extract_config;
mod get_absolute_path;
mod get_absolute_time;
mod get_bare;
mod get_branch_count;
mod get_commit_count;
mod get_contributor_summary;
mod get_current_branch;
mod get_current_commit_hash;
mod get_dirty;
mod get_relative_path;
mod get_relative_time;
mod get_repo_name;

pub use extract_config::extract_config;
pub use get_absolute_path::get_absolute_path;
pub use get_absolute_time::get_absolute_time;
pub use get_bare::get_bare;
pub use get_branch_count::get_branch_count;
pub use get_commit_count::get_commit_count;
pub use get_contributor_summary::get_contributor_summary;
pub use get_current_branch::get_current_branch;
pub use get_current_commit_hash::get_current_commit_hash;
pub use get_dirty::get_dirty;
pub use get_relative_path::get_relative_path;
pub use get_relative_time::get_relative_time;
pub use get_repo_name::get_repo_name;

pub const USER_NAME: &str = "user.name";
pub const USER_EMAIL: &str = "user.email";
